### ISSUE TITLE
Pagination for ActivityList is off by 1

### ISSUE THREAD

**Issue by ShiveringPenguin** [mvaneijken/GarminConnect#1]
PageSize increments by 100, but activities are indexed starting at zero.  

Therefore:
Page 1 = Records 0-99
Page 2 = Records 100-198
Page 3 = Records 199-297
... etc

I believe you need to increment $FirstRecord as follows:
#    $FirstRecord = $FirstRecord + $PageSize
    $FirstRecord = $FirstRecord + $PageSize - 1

Thanks for your work on this script.

**Comment by ShiveringPenguin** [comment]
Update:
I apologize for my first post.  I reported "my solution" rather than "my problem".

Here is my problem:
I noticed a mileage discrepancy between Garmin Connect app and the output of this script.  The mileage reported from this script was always less than Connect.  I was able to trace the problem to missing activities.  Specifically, every 100th activity (100, 200, 300, etc) was missing from the script output.  When I logged new activities, a new set of activities would go missing, but they were always missing at the x*100 index.

I was able to retrieve my complete set of activities by implementing the fix I reported above.  However, I think I stumbled onto a fix that wasn't actually targeting the root problem.

By default, Garmin Connect reports 99 activities.  Note how many records are returned when you call the API [with no variables](https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities).

Knowing this, it appears your "limit" variable is not being passed correctly to the API.  I printed the url call from your script and found that there may be a misplaced question mark leading to a double "??".
See: https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities??limit=100&start=0
Notice how changing the [limit=10](https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities??limit=10&start=0) still returns 99 records.

Do you think the double question marks may be spoiling the "limit" variable?

Using the following fix, and I can now reliably retrieve my complete dataset.  My mileage totals now match those reported from Garmin Connect app.
```
#    $SearchResults = Invoke-RestMethod -Uri $ActivitySearchURL"?limit=$PageSize&start=$FirstRecord" -method get -WebSession $GarminConnectSession -ErrorAction SilentlyContinue
    $SearchResults = Invoke-RestMethod -Uri $ActivitySearchURL"limit=$PageSize&start=$FirstRecord" -method get -WebSession $GarminConnectSession -ErrorAction SilentlyContinue
    $ActivityList += $SearchResults
    $FirstRecord = $FirstRecord + $PageSize
#    $FirstRecord = $FirstRecord + $PageSize - 1
    $Pages++
```

I hope this is helpful.

**Comment by mvaneijken** [comment]
Thanks for reporting, indeed there was a double questionmark symbol in the request URL. It is removed from the GCSettings xml and it works as it should.
