### ISSUE TITLE
402 Error

### ISSUE THREAD

**Issue by ShiveringPenguin** [mvaneijken/GarminConnect#2]
Around Feb 21, this script started throwing a 402 error.  

The error is thrown on line 246:
`    $SearchResults = Invoke-RestMethod -Uri $ActivitySearchURL"?limit=$PageSize&start=$FirstRecord" -method get -WebSession $GarminConnectSession -ErrorAction SilentlyContinue`

I think the Garmin Connect website changed around the same time so I suspect the problem resides server-side.  Perhaps there was another change to authentication?

**Comment by ShiveringPenguin** [comment]
Per [this post](https://github.com/petergardfjall/garminexport/commit/b62e2ac1e53b8af8f69be64dd7153301f119f607), it looks like the API endpoint changed.  Removing "modern" from the urls listed in GCProgramSettings.xml fixed the 402 error for me. 

Note, the post from petergardfjall also indicates that a CSRF token is now required during authentication.

**Comment by mvaneijken** [comment]
This error occurs due a header issue. They are selling a paid API and it probably sees that it is not a real browser. Added a fix where the headers are enriched as with a real session.
